### ISSUE TITLE
Glide version 0.3.0

### ISSUE THREAD

**Issue by reinink** [freekmurze/laravel-glide#1]
Hey @freekmurze, thanks so much for putting this library together. I just wanted to let you know that I just released Glide version 0.3.0. I'll be honest, this release has many breaking changes from version 0.2.x. I apologize for that, but I did want to make all significant changes prior to an eventual 1.0 release. You can find the changelog [here](http://glide.thephpleague.com/changelog/).

I will note that I designed version 0.3.0 with Laravel 5 in mind. In fact, Taylor was even kind enough to accept [a tweak](https://github.com/laravel/framework/pull/7005) to the new filesystem adapter in Laravel 5 to to allow access to underlying Flysystem driver. This allows you to use the already configured Flysystem instance with Glide. Here is a rough example:

``` php
$this->app->singleton('League\Glide\Server', function ($app) {

    $filesystem = $this->app->make('Illuminate\Contracts\Filesystem\Filesystem');

    return League\Glide\ServerFactory::create([
        'source' => $filesystem->getDriver(),
        'cache' => $filesystem->getDriver(),
        'source_path_prefix' => 'path/to/source/images',
        'cache_path_prefix' => 'path/to/image/cache',
    ]);
});
```

Laravel 5 was also a big reason why I added the new `source_path_prefix` and `cache_path_prefix` options. Normally you would just set this when create your `Flysystem` objects, but since you only have one instance available in Laravel 5 you need a way to set the source and cache paths at the `Server` level.

You'll also notice that I rearranged the [folder structure](https://github.com/thephpleague/glide/tree/master/src) significantly in this version as well, so there are a bunch of new class names and namespaces. This was a bit painful, but I think it was a good move thinking long term.

Just thought I'd touch base and bring you up to speed on all this! :)

**Comment by freekmurze** [comment]
Hi @reinink,

thanks for letting me know. I'll implement the necessary changes in my package during the coming weeks.

And also a big thank you for keeping Glide awesome! :+1:

**Comment by freekmurze** [comment]
The new version 0.3.0 of this package is compatible with Glide 0.3.0.

**Comment by reinink** [comment]
Awesome! :)

**Comment by reinink** [comment]
And not telling you what to do, but have you considered a slightly less verbose API? I haven't thought this through too much, but I'm thinking something like this:

``` php
<img src="{{ Glide::image('kayaks.jpg')->modify(['w' => 50, 'filt' => 'greyscale']) }}" />
```

Or even:

``` php
<img src="{{ Glide::image('kayaks.jpg', ['w' => 50, 'filt' => 'greyscale']) }}" />
```

Or even extending Blade?

``` php
<img src="@image('kayaks.jpg', ['w' => 50, 'filt' => 'greyscale'])" />
```

Just an idea, that's all! :stuck_out_tongue_winking_eye:

**Comment by freekmurze** [comment]
Thanks for your fine suggestions! I'll probably change the API a bit in that direction you're pointing to. 

Next week I plan on playing with the stable release of Laravel 5 quite a bit and I'll look into extending Blade.

**Comment by reinink** [comment]
Good stuff Freek, and again I didn't think through it too much, so keep that in mind. ;)

**Comment by freekmurze** [comment]
Hi @reinink,

just wanted to let you know that we followed a few of your suggestions for making the API somewhat less verbose. The package is now also L5 compatible. 

I also plann on using the already configured L5 Flysystem instance in the next release.

**Comment by reinink** [comment]
Awesome dude! Good stuff. :+1:
