### ISSUE TITLE
Non-secure urls (no signatures) option

### ISSUE THREAD

**Issue by artemverbo** [freekmurze/laravel-glide#13]
Hello! 

First of all thank you for the project, nice one! 

Could you advise please, I'm trying to use it with URLs generated from the Angular front-end, dynamically, so not using `GlideImage::load`, but something like `.../img/image.jpg?w=200` with image urls coming from a model. The problem is in that case I don't have a signature parameter and can't pass the 
`SignatureFactory::create($this->app['config']->get('app.key'))->validateRequest($request);` validator. So was thinking, maybe the signature should be optional? I believe in Glide they say it's an "additional security feature", I totally understand the purpose, but don't see an easy solution in my case. Do you have any suggestions or workarounds?

Thank you!

**Comment by freekmurze** [comment]
Hi,

I make the signature optional in a future version (I can cook that up within 30 days or so).

But if you feel you're up for it, feel free to submit a pull request.

**Comment by freekmurze** [comment]
Hi, I've accepted the pull request, made some small changes and tagged it as version 2.1.0.
Have fun with this package.
