### ISSUE TITLE
"Signature is missing"

### ISSUE THREAD

**Issue by rombat** [freekmurze/laravel-glide#17]
Hi,
I have this error
``` exception 'League\Glide\Http\SignatureException' with message 'Signature is missing.' in /home/devmg/public_html/laravel/vendor/league/glide/src/Http/Signature.php:43 ```
and I can't figure out what is the problem. Can somebody help me?
I'm using Laravel 4.2 by the way.

**Comment by MatthiasDeWinter** [comment]
Hi,

Make sure you install the package correctly for Laravel 4, setting the service provider and facade.
Publishing the config-file is `php artisan config:publish spatie/laravel-glide`.

Is it possible to show some code of what you are trying to achieve or show me how to reproduce this error?

**Comment by rombat** [comment]
I have this in providers ```'Spatie\Glide\GlideServiceProvider',```, this in aliases ```'GlideImage'        => 'Spatie\Glide\GlideImageFacade',``` and my laravel Glide config is:
```
<?php

return [
    /*
     * Glide will search for images in this directory
     *
     */
    'source' => [
        'path' => public_path('img/produits'),
    ],

    /*
     * The directory Glide will use to store it's cache
     * A .gitignore file will be automatically placed in this directory
     * so you don't accidentally end up committing these images
     *
     */
    'cache' => [
        'path' => storage_path('glide-cache'),
    ],

    /*
     * URLs to generated images will start with this string
     *
     */
    'baseURL' => 'img',

    /*
     * The maximum allowed total image size in pixels
     */
    'maxSize' => 2000 * 2000
];
```

I load my picture with ```<img src="{{ GlideImage::load($produit->imagesCarousel()[0], ['w'=> 210]) }}" />```

Here's what is rendered in my view:
```
<img src="/img/6400-6400L-6400B%2Fvisuel%2F6400-6400L-6400B_IMG_01.jpg?w=210&amp;s=4de60d1bbf45511b4a3227fdca65eeb4" >
```

And here's the exception:
```
[2015-03-27 13:19:09] local.ERROR: exception 'League\Glide\Http\SignatureException' with message 'Signature is missing.' in D:\lamp\www\laravel\vendor\league\glide\src\Http\Signature.php:43

Stack trace:
#0 D:\lamp\www\laravel\vendor\spatie\laravel-glide\src\Spatie\Glide\GlideServiceProvider.php(34): League\Glide\Http\Signature->validateRequest(Object(Illuminate\Http\Request))
#1 [internal function]: Spatie\Glide\GlideServiceProvider->Spatie\Glide\{closure}('produits/K974/p...')
#2 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Routing\Route.php(109): call_user_func_array(Object(Closure), Array)
#3 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1033): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#4 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Routing\Router.php(1001): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#5 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(775): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#6 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(745): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#7 D:\lamp\www\laravel\vendor\barryvdh\laravel-debugbar\src\Middleware\Stack.php(34): Illuminate\Foundation\Application->handle(Object(Illuminate\Http\Request), 1, true)
#8 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Session\Middleware.php(72): Barryvdh\Debugbar\Middleware\Stack->handle(Object(Illuminate\Http\Request), 1, true)
#9 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Cookie\Queue.php(47): Illuminate\Session\Middleware->handle(Object(Illuminate\Http\Request), 1, true)
#10 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Cookie\Guard.php(51): Illuminate\Cookie\Queue->handle(Object(Illuminate\Http\Request), 1, true)
#11 D:\lamp\www\laravel\vendor\stack\builder\src\Stack\StackedHttpKernel.php(23): Illuminate\Cookie\Guard->handle(Object(Illuminate\Http\Request), 1, true)
#12 D:\lamp\www\laravel\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(641): Stack\StackedHttpKernel->handle(Object(Illuminate\Http\Request))
#13 D:\lamp\www\laravel\public\index.php(49): Illuminate\Foundation\Application->run()
#14 {main} [] []
```

**Comment by MatthiasDeWinter** [comment]
Allright,

I have found where the package breaks on your end.

In the rendered view, the Ampersand is URLencoded. 
So `&` becomes `&amp;` , because of this the Signature can't be read from the generated URL, hence Glide thinks it's just missing.

No idea why this is happening on your machine but not on mine, but I will let you know as soon as I do.

Maybe temporary you can filter `amp;` out of the generated url.

**Comment by verybigelephants** [comment]
I know this is old but i have recently encountered the same error on an old project, without any knowledge that we were even using signed images.

In my case it was that when we were including any arbitrary image in `public/img` directory and the file didn't exist, spatie/laravel-glide thought that this is some kind of dynamic image and tired to load it via this library, producing gigabytes of error logs over the years where nobody noticed that a single image called "header-mobile@2x.png?v=2" was missing from the '/img' directory.

Really no idea why laravel-glide tried to handle it
