### ISSUE TITLE
The image is not resizing

### ISSUE THREAD

**Issue by RaoulBivolaru** [freekmurze/laravel-glide#18]
So I followed all the steps and the image is loaded but with original dimensions.

All my images are in the public folder and from what I can see using a debugger in the GlideServiceProvider, the router is not working. Maybe because my images are not in the storage folder?

**Comment by MatthiasDeWinter** [comment]
Hi,

Could you show me your config-file, and how you load the images?

**Comment by RaoulBivolaru** [comment]
This is how I load the images
<img src="{{ GlideImage::load($user->profileImage['url'], ['w'=> 30]) }}" alt="{{$user->username}}"/>

And for the config file
'source' => [
        'path' => public_path('media'),
    ],
    'cache' => [
        'path' => storage_path('glide/cache'),
    ],
    'baseURL' => 'media',
    'maxSize' => 2000 * 2000,
    'useSecureURLs' => true

**Comment by RaoulBivolaru** [comment]
This is how I load the images

```
     <img src="{{ GlideImage::load($user->profileImage['url'], ['w'=> 30]) }}" alt="{{$user->username}}"/>

```
And for the config file

```
'source' => [
        'path' => public_path('media'),
    ],
    'cache' => [
        'path' => storage_path('glide/cache'),
    ],
    'baseURL' => 'media',
    'maxSize' => 2000 * 2000,
    'useSecureURLs' => true

```

**Comment by MatthiasDeWinter** [comment]
Is the value of `$user->profileImage['url']` a path relative to `public_path('media')`?

**Comment by RaoulBivolaru** [comment]
Yes the path is something like photos/user/name of the image

**Comment by MatthiasDeWinter** [comment]
Ok.

Can you send me the generated url for an image?

Are you using Laravel 4 or 5?

**Comment by RaoulBivolaru** [comment]
I'm using Laravel 5 and this is how a url looks
```
/media/photos/james/03-04-2015_14-39-47_9qBTh.jpg?w=300&s=087846c0c6839575fe7f422ba829fc68
```
The image is showing.

**Comment by RaoulBivolaru** [comment]
Never mind, the problem was on my side. I didn't configure my server correctly. Thanks for your help anyway.

**Comment by eclatsujan** [comment]
i have same issue while generating image on my website http://www.aircraftsmuseum.com/
