### ISSUE TITLE
Incorrectly assumes the namespace is always "App"

### ISSUE THREAD

**Issue by akurtz** [freekmurze/laravel-glide#22]
From `/Spatie/Glide/Controller/GlideImageController.php`

```
use App\Http\Controllers\Controller;
```

This assumes that the application namespace is "App", which won't always be the case.  When the app namespace has been changed from the default, it causes a fatal error: `Class 'App\Http\Controllers\Controller' not found`.  I can change it manually, but every time the package is updated, it's going to revert.

Is there anything that can be done about this?  Could this be helpful?

https://github.com/laravel/framework/blob/5.0/src/Illuminate/Console/AppNamespaceDetectorTrait.php

**Comment by freekmurze** [comment]
This problem is solved in version 2.2.1
