### ISSUE TITLE
fix for L5

### ISSUE THREAD

**Issue by RonnieVisser** [freekmurze/laravel-glide#5]
Is this going to be fixed for laravel 5?

**Comment by freekmurze** [comment]
Yup, probably there will be a L5 compatible version by the end of the week.

On Tuesday, February 10, 2015, Ronnie Visser <notifications@github.com>
wrote:

> Is this going to be fixed for laravel 5?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freekmurze/laravel-glide/issues/5>.
>


-- 




Freek Van der Herten
Samberstraat 69 D
2060 Antwerpen
T:  +32 3 292 56 79
M: +32 495 84 27 91
https://spatie.be

**Comment by freekmurze** [comment]
Hi, version 2.0.0 adds Laravel 5 compatibility.
